elasticsearch:
  replicaCount: 3
  httpPort: 9200
  transportPort: 9300
  resources:
    limits:
      memory: 2Gi
    requests:
      memory: 1Gi
  backupImage: "MY_BACKUP_IMAGE:TAG"
  backupImagePullPolicy: "IfNotPresent"
  backupSchedule: "0 2 * * *"

kibana:
  port: 5601
