apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testcustoms.example.com
spec:
  group: example.com
  versions:
    - name: v1beta1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: testcustoms
    singular: testcustoms
    kind: MyCustom
    shortNames:
      - mc
