apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-elasticsearch
spec:
  replicas: {{ .Values.elasticsearch.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-elasticsearch
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
          ports:
            - containerPort: {{ .Values.elasticsearch.httpPort }}
            - containerPort: {{ .Values.elasticsearch.transportPort }}
          resources:
            limits:
              memory: {{ .Values.elasticsearch.resources.limits.memory }}
            requests:
              memory: {{ .Values.elasticsearch.resources.requests.memory }}
