apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-elasticsearch
spec:
  selector:
    app: {{ .Release.Name }}-elasticsearch
  ports:
    - name: http
      port: {{ .Values.elasticsearch.httpPort }}
      targetPort: {{ .Values.elasticsearch.httpPort }}
    - name: transport
      port: {{ .Values.elasticsearch.transportPort }}
      targetPort: {{ .Values.elasticsearch.transportPort }}
