apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-kibana
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.11.3
          ports:
            - containerPort: {{ .Values.kibana.port }}
          env:
            - name: ELASTICSEARCH_URL
              value: "http://{{ .Release.Name }}-elasticsearch:{{ .Values.elasticsearch.httpPort }}"
