apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kibana
spec:
  selector:
    app: {{ .Release.Name }}-kibana
  ports:
    - name: http
      port: {{ .Values.kibana.port }}
      targetPort: {{ .Values.kibana.port }}
